### ISSUE TITLE
Piranha.EF: Db needs virtual properties

### ISSUE THREAD

**Issue by willwolfram18** [TheWolfA2/piranha.core#2]
### Problem
The `Piranha.EF.Db` class's `DbSet` properties are not marked as virtual. Because of this, `Moq` won't be able to mock the properties for testing of repository implementations

### Possible Solutions
* Mark `DbSet` properties as virtual

**Comment by willwolfram18** [comment]
Just noticed that `Piranha.EF.Db` is a sealed class, and therefore cannot have virtual properties. This should like be refactored to inherit from an `internal Piranha.EF.IDb` so that unit tests can be written to verify the repository implementations. This would also mean updating all constructor/properties within the /src/data folder to use the new `Piranha.EF.IDb`.

Thoughts on this, @tidyui?

**Comment by tidyui** [comment]
Since Unit Testing is not my field of expertise I'll just write the thoughts behind the current architecture and you can evaluate from a Unit Testing perspective.

### Sealed DbContext
The Db context should never be extended by the users, it is an internal object of the Entity Framework implementation of the repositories. The reason for the class being public is that users should be able to add repository extensions which can then access use the DbContext for custom queries.

### Mocking the DbContext
The `IApi` is injected an `IDataService`. Piranha.EF implements the `IDataService` interface for Entity Framework. Instead of overriding properties in the DbContext a mock Data Service should be created (or at least that was my idea behind it).

Let me know if the clarifies and solves the issue!

Regards

**Comment by willwolfram18** [comment]
I should start off by saying that unit tests are also not my area of expertise, but I have been trying to improve my understanding of TDD, and writing good unit tests to help improve projects.

I'm realizing I wrote this issue, but didn't actually clarify why I wrote it. I want to make unit tests for each of the `I*Repository` implementations. In order to accomplish this, I need to be able instantiate the repository object and give it some in memory data to test on, which means I need to use their default constructors. This in turn means I need to be able to inject an instance of `Piranha.EF.Db` into the object to perform testing and provide the repo with the data.

### Sealed DbContext
This totally makes sense, and I 100% agree with making it sealed; it shouldn't be manipulated publicly. With that being said, I'm thinking an `internal Piranha.EF.IDb` would be the best option that `Piranha.EF.Db` then implements. I believe it would require the least amount of refactoring, and realistically wouldn't make any functional changes.

#### Why `IDb`?
Apologies if this is redundant information or you're already aware of this!

The reason we need either an interface or `virtual` properties/methods is so that mocking frameworks, such as `Moq`, can create proxy implementations of those properties/methods. If the method can't be overridden then `Moq` can't intercept it and inject an artificial result. With an `IDb`, however,  we can do the following for a `PageRepository` unit test
```
var mockDb = new Mock<IDb>();
mockDb.Setup(d => d.Pages).Returns(new List<Page> {
    // in memory Page objects
}.AsQueryable());
var pageRepo = new PageRepository(mockDb.Object);
var page = pageRepo.Query();
// runs the Pagerepository.Query method, but operates on the data we
// povided during the .Setup().Returns() call
```

### Mocking the DbContext
If I'm understanding correctly, you were thinking an `IApi` instance would have an `IDataService` injected, which can then have unit tests done on it, or be used for injection into other tests, such as `PageController`. This is actually already achievable, since there is already an `IApi` that can be `Moq`ed, and is in fact what's going on in the Manager controller unit tests. But when it comes to testing the implementations in `Piranha.EF`, the repos are tightly bound to `Db` and `DataService`, preventing them from being `Moq`ed properly and tested.

### Conclusion
I think a `Piranha.EF.IDb` should be created, which can then be used for injecting `Mock<IDb>` objects into repo implementations for unit testing. Furthermore, in order to create these repo tests `Piranha.EF` will need to use the [InternalsVisibleToAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.internalsvisibletoattribute(v=vs.110).aspx). 

-------

### Sidebar
Why do only some of the `Piranha.EF.Repositories` derive from `RepositoryBase<T, TModel>`? My first assumption was that it had to do with a `TModel` not having a matching `Extend.T` to pair with, but I see that `BlockTypeRepository` doesn't derive from `RepositoryBase` even though there is a `Extend.BlockType`. Is there a particular design logic behind this, or was this an accident? If it was an accident, would you like me to take the time to fix it while handling the `IDb` refactor?

**Comment by tidyui** [comment]
I see, I never intended for the repositories to be created outside of the DataService which is why all constructors are **internal** as well:

https://github.com/PiranhaCMS/piranha.core/blob/master/src/data/Piranha.EF/Repositories/BlockTypeRepository.cs#L31

Now if you have a solution on how to maintain a good secure code structure and still being able to mock the DbContext for testing the repositories by all means go ahead. 

Regarding the PageType/BlockType repositories not deriving from RepositoryBase it's probably just a miss but we don't need to invest to much time into these right now, I thinking about removing/disabling them for the first version as types will be import only.

**Comment by willwolfram18** [comment]
Handled in 7aa6c98 using an interface
